packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@solidjs/testing-library": 1.0.0-beta.3
  "@solidjs/web": 2.0.0-rc.6
  "@testing-library/jest-dom": ^6.9.1
  "@types/node": ^24
  comark: ^0.6.2
  jsdom: ^30.0.1
  markdown-exit: ^1.3.0
  markdown-it-cjk-friendly: ^3.0.0
  solid-js: 2.0.0-rc.6
  typescript: ^7.0.2
  unplugin-solid: ^2.0.0
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
overrides:
  vite@*: "catalog:"
  babel-preset-solid: 2.0.0-rc.2
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
